import sys
import random
#winner tells us who wins
def winner(player,computer1,board): #statement and conditions are who ever wins the value of count changes respectively.
    count = 0
    if board[player]==board[0] and computer1==board[2]:
        count = 1
    if board[player]==board[1] and computer1==board[0]:
        count = 1
    if board[player]==board[2] and computer1==board[1]:
        count =1
    if board[player]==computer1:
        count =0
    elif board[player]!=computer1:
        count =2
    return count
    #end of win method
def displayprogress(computer1,player,board): # display the progress who chooses who!!!
    print('Computer1 move:',computer1)
    print('Player1 move:',board[player])
#end of displayprogress(computer1,computer2,player)
def display(board): #display the board of the game
    print('0:'+ board[0])
    print('1:'+board[1])
    print('2:'+board[2])
def introduction(): #introduce the game
    print('GREETINGS-----Fellas')
    try:
        user = input('Do you want to play game?Yes/No:').lower()
        if user=='yes':
            mainmethod()
            if user=='no':
                sys.exit()
    except:
        print('Integer value ain\'t allowed.')
        introduction()
        #exception if user type anything else rather than typing yes or no!!!
def compmove(board): #random moves by compute two times there will be 2 values generated by computer
    comp=random.choice(board)
    return comp #end of computer move method
def player_move(board): #player_move() method
#Exception handling is done just in case that if the player does not presses any integer value
        try:
            player=int(input('What do you want to choose:'))
            if player<=len(board)-1 and player >=0: #check if player actually enters the value in boundaries...
                return player
            else:
                print('Enter the choice again(0-2):') #if not it gives an error and again same function is called
                player_move(board)
        except:
            print('It should be only Positive-Integer')
            player_move(board)
def mainmethod(): # main method where it all begins
    while True:    #Run till the game is not over and user does not want to play
        board=['rock','paper','scissor']
        display(board)
        player=player_move(board)
        computer1=compmove(board)
        displayprogress(computer1,player,board)
        win =winner(player,computer1,board)
        print(win)
        if win==0:
            print('No one has won')
            break
        elif win ==1:
            print('The player has won')
            break
        elif win == 2:
            print('The computer has won')
            break
#while loop will end when run flag will have false in it.
#end of mainmethod
introduction()
mainmethod()
